language: node_js
node_js: stable
script:
  - npm install
  - hexo generate
  - hexo deploy

git:
  depth: 1

branches:
  only:
    - hexo

before_install:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in .travis/deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval $(ssh-agent)
  - ssh-add deploy_key
