language: node_js
node_js: stable
script:
  - npm install
  - hexo generate

branches:
  only:
    - hexo

before_deploy:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
    
deploy:
  provider: pages
  cleanup: false
  local_dir: public
  target_branch: master
  deploy_key: deploy_key
